require:
  - rubocop-erb
AllCops:
  Exclude:
    - 'lib/au_core_test_kit/custom_groups/request_logger.rb'
    - 'lib/au_core_test_kit/custom_groups/provenance_validator.rb'
    - 'lib/au_core_test_kit/custom_groups/helpers.rb'
    - 'lib/au_core_test_kit/custom_groups/clinical_note_type_test.rb'
    - 'lib/au_core_test_kit/custom_groups/smart_app_launch_group.rb'
    - 'lib/au_core_test_kit/custom_groups/v0.3.0-ballot/capability_statement_group.rb'
    - 'lib/au_core_test_kit/custom_groups/fhir_resource_navigation.rb'
    - 'lib/au_core_test_kit/custom_groups/date_search_validation.rb'
    - 'lib/au_core_test_kit/custom_groups/v0.3.0-ballot/profile_support_test.rb'
    - 'lib/au_core_test_kit/generated/v0.3.0-ballot/au_core_test_suite.rb'
    - 'lib/au_core_test_kit/custom_groups/special_identifier_search_test.rb'
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Naming/ClassAndModuleCamelCase:
  Enabled: false
