development:
  adapter: sqlite
  database: data/inferno_development.db
  max_connections: 10
  # user:
  # password:
  # host:
  # port:

production:
  adapter: postgres
  host: <%= ENV['POSTGRES_HOST'] %>
  port: <%= ENV.fetch('POSTGRES_PORT', 5432).to_i %>
  database: <%= ENV['POSTGRES_DB'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: "<%= ENV['POSTGRES_PASSWORD'] %>"

test:
  adapter: sqlite
  database: ':memory:'
  max_connections: 10
